return {
	vim.keymap.set({ 'n', 'v' }, '<Space>', '<Nop>', { silent = true }),
	vim.keymap.set('n', 'k', "v:count == 0 ? 'gk' : 'k'", { expr = true, silent = true }),
	vim.keymap.set('n', 'j', "v:count == 0 ? 'gj' : 'j'", { expr = true, silent = true }),
	vim.keymap.set('n', '<leader>sf', require('telescope.builtin').find_files, { desc = '[S]earch [F]iles' }),
	vim.keymap.set('n', '<leader>sr', require('telescope.builtin').oldfiles, { desc = '[S]earch [F]iles' }),
	vim.keymap.set('n', '<leader>sh', require('telescope.builtin').help_tags, { desc = '[S]earch [H]elp' }),
	vim.keymap.set('n', '<leader>sg', require('telescope.builtin').live_grep, { desc = '[S]earch by [G]rep' }),
	vim.keymap.set('n', '<leader>w', ':w<cr>', { desc = 'Save' }),
	vim.keymap.set('n', '<leader>q', ':q<cr>', { desc = 'Quit' }),
	vim.keymap.set('n', '<leader>e', ':NvimTreeToggle<cr>', { desc = 'Explorer' }),
	vim.keymap.set('n', '<C-h>', '<C-w>h' ),
	vim.keymap.set('n', '<C-j>', '<C-w>j' ),
	vim.keymap.set('n', '<C-k>', '<C-w>k' ),
	vim.cmd("noremap <up> <nop>"),
	vim.cmd("noremap <Down> <Nop>"),
	vim.cmd("noremap <Left> <Nop>"),
	vim.cmd("noremap <Right> <Nop>"),
	vim.cmd("inoremap <Up> <Nop>"),
	vim.cmd("inoremap <Down> <Nop>"),
	vim.cmd("inoremap <Left> <Nop>"),
	vim.cmd("inoremap <Right> <Nop>"),
	vim.cmd("vnoremap im aBoV"),
	vim.cmd("nnoremap J 5j"),
	vim.cmd("nnoremap K 5k"),
	vim.cmd('nnoremap "" vi"'),
	vim.cmd("vnoremap am aBjoV"),
	vim.keymap.set("v", "J", ":m '>+1<CR>gv=gv"),
	vim.keymap.set("v", "K", ":m '<-2<CR>gv=gv"),


}
